name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    # Step 3: Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/blazebytehungary/hasznaltauto-figyelo:master

    # Step 4: Push the Docker image to GHCR
    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/blazebytehungary/hasznaltauto-figyelo:master
